version: "3.5"

services:
  digiteam_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "digiteam_app"
    ports:
      - "88:80"
    # volumes:
    #   - ./../:/var/www/html
    # command: "php /var/www/html/artisan octane:start --host=0.0.0.0 --port=80"

  psql:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    # ports:
    #   - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
