name: Backend Research v4

on:
  push:
    branches: [main]
    paths:
      - 'architecture-v4/**'

jobs:
  trigger:
    name: Trigger Backend Research v4
    runs-on: ubuntu-latest
    steps:
      - name: Call Jenkins
        run: curl --user "deployer:${{ secrets.JENKINS_PWD }}" https://jenkins.digitalservice.id/${{ secrets.JENKINS_TOKEN_V4 }}