name: Backend Research v2

on:
  push:
    branches: [main]
    paths:
      - 'v2-sd-with-library/**'

jobs:
  trigger:
    name: Trigger Backend Research v2
    runs-on: ubuntu-latest
    steps:
      - name: Call Jenkins
        run: curl --user "deployer:${{ secrets.JENKINS_PWD }}" https://jenkins.digitalservice.id/${{ secrets.JENKINS_TOKEN_V2 }}