name: Digiteam v2 Riset

on:
  push:
    branches: [main]

jobs:
  trigger:
    name: Call Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Call Jenkins
        run: curl --user "deployer:${{ secrets.JENKINS_PWD }}" https://jenkins.digitalservice.id/${{ secrets.JENKINS_TOKEN_NAME }}