name: Backend Research v3

on:
  push:
    branches: [main]
    paths:
      - 'v3-md-without-library/**'

jobs:
  trigger:
    name: Trigger Backend Research v3
    runs-on: ubuntu-latest
    steps:
      - name: Call Jenkins
        run: curl --user "deployer:${{ secrets.JENKINS_PWD }}" https://jenkins.digitalservice.id/${{ secrets.JENKINS_TOKEN_V3 }}